databases:
  - name: feiteng
    username: kylin
    passwd: kylin
    hostname: localhost
    type: QMYSQL
    database: admindatabase
  - name: info
    username: kylin
    passwd: kylin
    hostname: localhost
    type: QMYSQL
    database: studentdatabase